name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      email: ${{ secrets.email }}
      password: ${{ secrets.password }}
      baseUrl: ${{ secrets.baseUrl }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      # NEXT_BASE_HTTP: ${{ secrets.NEXT_BASE_HTTP }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      NEXT_PUBLIC_HTTP: ${{ secrets.NEXT_PUBLIC_HTTP }}
    steps:
      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: run install, build and test

        run: |
          yarn 
          yarn build
          yarn test
