name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          build: yarn build
          start: yarn start
          run: yarn test
          wait-on: "http://localhost:3000"
          # parallel: true
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          baseUrl: ${{ secrets.baseUrl }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # NEXT_BASE_HTTP: ${{ secrets.NEXT_BASE_HTTP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NEXT_PUBLIC_HTTP: ${{ secrets.NEXT_PUBLIC_HTTP }}
